on Hostname = res-hpc-lkeb03
on GPU      = 0

@ Sun Jul 21 20:34:16 CEST 2019

Traceback (most recent call last):
  File "/exports/lkeb-hpc/syousefi/2-lkeb-17-dl01/syousefi/TestCode/EsophagusProject/sythesize_code/synthesize_asl_loss/CodeCluster-GP/backup-20190721_200339/run.py", line 30, in <module>
    fold=fold,Server='DL',newdataset=True,mixedup=mixedup,l_regu=l_regu)
  File "/exports/lkeb-hpc/syousefi/2-lkeb-17-dl01/syousefi/TestCode/EsophagusProject/sythesize_code/synthesize_asl_loss/CodeCluster-GP/backup-20190721_200339/functions/call_synthesize_net_perceptual_net.py", line 86, in __init__
    logger.set_log_file(self.parent_path + self.Logs + self.log_ext + '/log_file' + str(fold))
  File "/exports/lkeb-hpc/syousefi/2-lkeb-17-dl01/syousefi/TestCode/EsophagusProject/sythesize_code/synthesize_asl_loss/CodeCluster-GP/backup-20190721_200339/functions/utils/logger.py", line 45, in set_log_file
    os.makedirs(log_folder)
  File "/exports/lkeb-hpc/syousefi/TF1LO/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/exports/lkeb-hpc/syousefi/TF1LO/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/exports/lkeb-hpc/syousefi/TF1LO/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 5 more times]
  File "/exports/lkeb-hpc/syousefi/TF1LO/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/srv/2-lkeb-17-dl01'
